name: Build SistemTakip

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SistemTakip/SistemTakip.csproj

    - name: Build
      run: dotnet publish SistemTakip/SistemTakip.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: SistemTakip-EXE
        path: publish/**
